### ISSUE TITLE
No support for sub-protocols

### ISSUE THREAD

**Issue by wbramw** [dpallot/simple-websocket-server#36]
Thanks to this great script, I got a websocket server up and running very quickly, so thank a lot for this!
Unfortunately one of the web clients that needs to connect to this, has a sub-protocol defined when setting up the websocket connection.
Is there any support for this in this websocket server?

**Comment by dpallot** [comment]
Can you elaborate on what sub-protocol you are referring to?

**Comment by YonathanB** [comment]
I think I have the same issue here.
Please take a look at that isse: https://stackoverflow.com/questions/34198566/websocket-error-during-websocket-handshake-sent-non-empty-sec-websocket-proto

**Comment by alfem** [comment]
Yes, I have got the same issue. Using a python websocket library to connect with this server the connection drops with an error like this:

Traceback (most recent call last):
  File "/home/alfem/acala/prog/help-channel/tests/pycos/__init__.py", line 3676, in _schedule
    retval = task._generator.send(task._value)
  File "./hctunnel.py", line 70, in hcwst
    ws.connect(repeater_ws, subprotocols=["binary"],sockopt=(socket.IPPROTO_TCP, socket.TCP_NODELAY))
  File "/home/alfem/acala/prog/help-channel/tests/websocket/_core.py", line 220, in connect
    self.handshake_response = handshake(self.sock, *addrs, **options)
  File "/home/alfem/acala/prog/help-channel/tests/websocket/_handshake.py", line 70, in handshake
    success, subproto = _validate(resp, key, options.get("subprotocols"))
  File "/home/alfem/acala/prog/help-channel/tests/websocket/_handshake.py", line 157, in _validate
    subproto = headers.get("sec-websocket-protocol", None).lower()
AttributeError: 'NoneType' object has no attribute 'lower'

If I check the headers array, my client is not receiving that 'sec-websocket-protocol'.
