### ISSUE TITLE
ssl connection crashed on python 2.7

### ISSUE THREAD

**Issue by xianzhaowang** [dpallot/simple-websocket-server#52]
once click the connection with ssl enabled(wss), the example crash like

 python SimpleExampleServer.py --example chat --ssl 1 --cert ./cert.pem 
Traceback (most recent call last):
  File "SimpleExampleServer.py", line 71, in <module>
    server.serveforever()
  File "/root/kw/wss/SimpleWebSocketServer.py", line 696, in serveforever
    super(SimpleSSLWebSocketServer, self).serveforever()
  File "/root/kw/wss/SimpleWebSocketServer.py", line 654, in serveforever
    client.handleClose()
  File "SimpleExampleServer.py", line 38, in handleClose
    clients.remove(self)
ValueError: list.remove(x): x not in list

**Comment by dpallot** [comment]
Thanks for that. I changed it so we only call handleClose if we have a successful handshake.

**Comment by xianzhaowang** [comment]
Thanks Dave for your response. May I know any reason for the negotiation
failure?
