### ISSUE TITLE
Exception: local variable 'sock' referenced before assignment

### ISSUE THREAD

**Issue by alexey-v-paramonov** [dpallot/simple-websocket-server#71]
Full trace:
```
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib64/python2.7/threading.py", line 812, in __bootstrap_inner
  File "/usr/lib64/python2.7/threading.py", line 765, in run
  File "/home/player2/track_scanner/scan.py", line 454, in ws
  File "/home/player2/track_scanner/SimpleWebSocketServer/SimpleWebSocketServer.py", line 703, in serveforever
  File "/home/player2/track_scanner/SimpleWebSocketServer/SimpleWebSocketServer.py", line 677, in serveforever
  File "/home/player2/track_scanner/SimpleWebSocketServer/SimpleWebSocketServer.py", line 650, in serveonce
UnboundLocalError: local variable 'sock' referenced before assignment

```

**Comment by alexey-v-paramonov** [comment]
See my PR #72
